sentinel-hub/eo-learn

docs/source/eolearn.core.core_tasks.rst
docs/source/eolearn.core.feature_types.rst
docs/source/eolearn.io.geopedia.rst
docs/source/eolearn.io.rst
docs/source/eolearn.io.sentinelhub_service.rst
docs/source/eolearn.io.sh_add.rst
docs/source/eolearn.io.sh_input.rst
docs/source/eolearn.mask.masking.rst
docs/source/eolearn.mask.rst

* update module names in eolearn.io
* update module names in eolearn.mask
* fixed warnings regarding length of underscore titles

update docs to latest stable release with new module names

---

core/eolearn/core/__init__.py
core/eolearn/core/constants.py
core/eolearn/core/eodata.py
core/eolearn/core/eoexecution.py
core/eolearn/core/eoworkflow.py
core/eolearn/core/utilities.py
core/eolearn/tests/test_eodata.py
core/eolearn/tests/test_eoexecutor.py
docs/source/eolearn.core.constants.rst
docs/source/eolearn.core.feature_types.rst
docs/source/eolearn.core.rst
features/eolearn/features/blob.py

Improvements of saving and loading functionalities of `EOPatch`. Implemented 3 levels of overwriting permissions.
Also a few other minor fixes.

Eopatch save

---

coregistration/eolearn/coregistration/coregistration.py
ml_tools/eolearn/ml_tools/classifier.py

fix docstrings for correct display

---

io/eolearn/io/sentinelhub_service.py

It might be premature to add it now considering no examples based on S1 GRD data are provided on readthedocs, but it still took me a little too long to figure out how to query S1 IW data.
I don't think it hurts to have it available already for testing purposes.

Add class S1IWWCSInput() and class S1IWWMSInput()

---

io/eolearn/io/sentinelhub_service.py
io/eolearn/tests/test_io.py

change condition such that time independent fields cannot overwrite existing time-stamps (see issue #22 )

Bugfix issue 22

---

core/eolearn/core/eodata.py
core/eolearn/tests/test_eodata.py

rename_feature was added alongside remove_feature and add_feature for quick use without needing to set up a workflow.

Add rename_feature definition

---

core/eolearn/core/eodata.py

Fixed a bug when reading a gzipped bounding box feature.

fixed a bug with loading gzipped bbox object

---

features/eolearn/features/interpolation.py

For linear interpolation scipy function is replaced by numpy.interp().

Linear numpy interpolation

---

io/eolearn/io/local_io.py

Added flag `create_dir` to function `_get_file_path` in `BaseLocalIo`. If set to `True` it creates the missing directories in the path. Useful for `EOTasks` that save files such as `ExportToTiff`.

ExportToTiff: Create dir if it doesn't exist

---

geometry/eolearn/geometry/morphology.py
geometry/eolearn/tests/test_morphology.py

- fixed erosion of only classes provided as erode_labels kwarg (all clases got eroded before)
- changed disk radius warning into a ValueError
- some refactoring to increase readability
- a minor test update

fixed ErosionTask

---

geometry/eolearn/geometry/transformations.py
geometry/eolearn/tests/test_transformations.py

I'm attaching a jupyter notebook to help visualize the behavior of polygon overlapping.
[polygon-overlap-test.zip](https://github.com/sentinel-hub/eo-learn/files/3465146/polygon-overlap-test.zip)

VectorToRaster polygon overlap

---

geometry/eolearn/geometry/transformations.py
geometry/eolearn/tests/test_transformations.py

Implemented polygon buffering before rasterization, mainly for eroding polygon before rasterizing them by using negative buffer arguments.

Added polygon buffering to VectorToRasterTask

---

core/eolearn/core/eodata.py
core/eolearn/core/eoexecution.py
core/eolearn/core/eoworkflow.py
geometry/eolearn/geometry/transformations.py

Handles case when vector dataframe is empty after buffering of geometries.

empty dataframe bug

---

README.md

This PR updates the installation instructions to include the `conda-forge` distribution

Update README to include conda forge installation

---

io/eolearn/io/processing_api.py
io/eolearn/tests/test_processing_io.py

- Added viewAzimuthMean, sunAzimuthAngles, sunZenithAngles.
- Individual bands get downloaded per-datatype (uint8, uint16, float32), each in their own .tiff, but all in all request, compressed into a .tar file.
- They then get extracted and assigned to the appropriate features.
This is a WIP PR, to get some comments while I work on it. Some refactoring is still needed.

Implemented additional data for processing api

---

io/eolearn/tests/test_processing_io.py

It turns out multiprocessing it's an important use case to detect breaking changes so I've added it as a test case.

Added a multiprocessing test case for the SentinelHubInputTask

---

README.md

Just a small update to the `README.md` file to include the `eo-learn` package that will install all subpackages in one through Conda-Forge.

tiny edit to conda install section of readme

---

mask/eolearn/mask/masking.py
mask/eolearn/tests/test_masking.py

This PR continues PR https://github.com/sentinel-hub/eo-learn/pull/195 and implements a more general masking for both time-dependent and time-independent spatial features. It also adds some unit tests.

MaskFeature task improvement

---

io/eolearn/io/processing_api.py

A minor fix of config parameter handling.

SentinelHubInputTask didn't pass config to SentinelHubReqest

---

core/eolearn/core/core_tasks.py

Fix naming in `LoadTask` for consistency

Fix docstrings for LoadTask

---

io/eolearn/io/local_io.py
io/eolearn/tests/test_local_io.py

This PR continues PR https://github.com/sentinel-hub/eo-learn/pull/200

ExportToTiff compress pararameter

---

io/eolearn/io/local_io.py
mask/eolearn/mask/masking.py

This suggested change adds the rasterio 'compress' option to the ExportToTiff task.
Apologies for the slightly dirty set of commits - forgot to branch first.

Add compress option for ExportToTiff

---

io/eolearn/io/processing_api.py
io/eolearn/tests/test_processing_io.py

Changed dtype of `dataMask` to boolean and a few minor things. Also added a few more tests.

Improved mask handling in SentinelHubInputTask

---

io/eolearn/io/processing_api.py
io/eolearn/tests/test_processing_io.py

- exposed parameter which is added to SH input data method
- added a test
- disabled a pylint for testing number of parameters (one to many :/)
I hope that's OK.

Expose option to add `other_args` to SH input data object

---

examples/crop-type-classification/Tasks/CropTypeClassTasks.py

* adds missing imports 
* makes sure that `Output/EOPatches` is created, if it doesn't exist already
* added utility function for getting a list of all available EOPatch names
* executed the notebook so that it also contains the outputs. For those who want to first just take a look at the process.

Minor improvements in crop classification example

---

core/eolearn/core/eodata_merge.py
core/eolearn/tests/test_eodata_merge.py
examples/io/SentinelHubIO.ipynb

- A few small improvements in merging EOPatches, particularly better error messages.
- Fixed some documentation links that didn't work.

Merge patch improvements

---

.travis.yml
visualization/eolearn/visualization/eopatch_visualization.py
visualization/eolearn/visualization/xarray_utils.py

This PR fixes 2 unrelated things:
- Plotting features with boolean values by casting values to uint8
- running pytest in Travis CI procedure - module with SH integration tests has been renamed

Fixed plotting boolean masks and minor CI update

---

.travis.yml
io/eolearn/tests/conftest.py
io/eolearn/tests/test_geometry_io.py
io/eolearn/tests/test_local_io.py

- Fixed cartopy issue according to https://github.com/SciTools/cartopy/issues/1767
- Fixed a few issues in the latest io tests
Tests at Travis CI now pass.

Fixed CI build and tests

---

geometry/eolearn/geometry/sampling.py

This is a quick improvement of the existing `PointSamplingTask` that allows defining a fraction of data to be sampled.
For more I would prefer to refactor sampling functionalities into a new more general task.

Added sampling_fraction parameter

---

core/eolearn/core/core_tasks.py
core/eolearn/core/eoworkflow.py
examples/core/CoreOverview.ipynb
examples/land-cover-map/extra_example-L1C.ipynb
examples/land-cover-map/extra_example-L2A.ipynb
examples/water-monitor/WaterMonitorWorkflow.ipynb
features/eolearn/features/bands_extraction.py
features/eolearn/tests/test_bands_extraction.py
io/eolearn/io/sentinelhub_process.py
io/eolearn/tests/test_sentinelhub_process.py

Every commit is a different minor fix or improvement, a couple of them reference the open GitHub issues.

Multiple minor improvements

---

core/eolearn/core/eodata_merge.py

Sorry for opening another PR. This one should optimize trivial cases where no real merging is required. In such cases no data will be changed or duplicated.

Time-dependent feature merging - memory optimization

---

.travis.yml
README.md
core/setup.py
coregistration/setup.py
features/setup.py
geometry/requirements.txt
geometry/setup.py
io/requirements.txt
io/setup.py
mask/setup.py
ml_tools/setup.py
pylintrc
setup.py
visualization/eolearn/visualization/eopatch_visualization.py
visualization/setup.py

Atm, tests don't pass yet but this will be fixed in next PRs

Travis migration, removed Python 3.6 support and added Python 3.9 support

---

core/eolearn/core/core_tasks.py
core/eolearn/core/eodata.py
core/eolearn/core/eodata_io.py
core/eolearn/core/eodata_merge.py
core/eolearn/core/eoexecution.py
core/eolearn/core/exceptions.py
core/eolearn/core/utilities.py
core/eolearn/tests/test_core_tasks.py
core/eolearn/tests/test_eodata.py
core/eolearn/tests/test_eodata_merge.py
coregistration/eolearn/coregistration/coregistration.py
features/eolearn/features/__init__.py
features/eolearn/features/haralick.py
features/eolearn/features/interpolation.py
features/eolearn/tests/test_interpolation.py
geometry/eolearn/geometry/superpixel.py
geometry/eolearn/geometry/transformations.py
geometry/eolearn/tests/test_superpixel.py
io/eolearn/io/local_io.py
io/eolearn/tests/test_local_io.py
mask/eolearn/mask/__init__.py
mask/eolearn/mask/cloud_mask.py
visualization/eolearn/visualization/eoexecutor_visualization.py

Changes:
- introduced custom eo-learn warning classes which were discussed in https://github.com/sentinel-hub/eo-learn/pull/347#discussion_r778708790
- cleaned up code that was deprecated for a while and updated tests.

Custom warnings and cleaning deprecations

---

core/eolearn/core/eoworkflow.py
core/eolearn/tests/test_eoworkflow.py

Small change to how arguments are passed to class method. Also adds a test making sure that duplicate nodes do not break the method.

Change how parameters are passed to from_endnodes

---

core/eolearn/core/eoexecution.py
core/eolearn/core/eoworkflow.py
core/eolearn/tests/test_eoexecutor.py
core/eolearn/tests/test_rayexecutor.py
visualization/eolearn/tests/test_eoexecutor_visualization.py
visualization/eolearn/visualization/eoexecutor_visualization.py
visualization/eolearn/visualization/report_templates/report.html

Changes:
- improves progress bar handling,
- improves logs handling and adds an option not to include them into the report
- showing task name next to stack trace
- nicer timestamp formatting in report
Note: I also added `filesystem` parameter but it is not used yet. That is still WIP and will be completed in the next PR.

EOExecutor improvements, part 2

---

core/eolearn/core/eodata.py
core/eolearn/core/eoexecution.py
core/eolearn/core/eonode.py
core/eolearn/core/eotask.py
core/eolearn/core/eoworkflow.py
core/eolearn/core/eoworkflow_tasks.py
core/eolearn/core/fs_utils.py
core/eolearn/tests/test_eoworkflow.py
features/eolearn/features/radiometric_normalization.py
io/eolearn/io/geopedia.py
io/eolearn/io/local_io.py
io/eolearn/tests/test_sentinelhub_process.py
ml_tools/eolearn/ml_tools/sampling.py
visualization/eolearn/visualization/eoexecutor_visualization.py
visualization/eolearn/visualization/eoworkflow_visualization.py

Since we recently started annotating our code mypy is starting to complain. This removes a fair amount of errors from the code without changing functionality (and without cluttering the code too much). There are also some small documentation changes.

Reduce amount of mypy warnings in eo-learn.core

---

features/eolearn/features/__init__.py
features/eolearn/features/feature_manipulation.py
features/eolearn/tests/test_feature_manipulation.py
mask/eolearn/mask/__init__.py
mask/eolearn/mask/masking.py
mask/eolearn/tests/test_masking.py

Adds two tasks that are commonly used.

Add JoinMasksTask and LinearFunctionTask

---

core/eolearn/core/eodata.py
core/eolearn/tests/test_eodata.py

EOPatch representation is now only showing feature types which have at least one defined feature.

EOPatch.__repr__ changes

---

core/eolearn/core/eodata_io.py

Handling the issue that happens with `fiona` `1.8.21`.

Fix for CRS deserialization

---

CHANGELOG.md

Feel free to edit directly on the branch.

Add 1.0 changes to changelog

---

core/eolearn/core/eodata_merge.py
core/eolearn/tests/test_eodata_merge.py

When merging eopatches with temporal features this optimization recognizes when the merge operation would not change anything for a given feature, saving time and (more importantly) memory.

Memory and speed optimization in simple eopatch merging procedures

---

core/MANIFEST.in
coregistration/MANIFEST.in
features/MANIFEST.in
geometry/MANIFEST.in
io/MANIFEST.in
mask/MANIFEST.in
ml_tools/MANIFEST.in
visualization/MANIFEST.in

- This way all requirements files will be included into the package.
- Regarding readme file, it seems that it is not necessary to write it into the manifest to be included in the package but I did it just in case.

Updated subpackage manifests to include all requirement files and readme

---

io/eolearn/io/local_io.py
io/eolearn/tests/test_local_io.py

I managed to refactor and extend functionalities in `ImportFromTiffTask`.

Improved ImportFromTiffTask to use rasterio Env

---

visualization/eolearn/tests/test_eoworkflow.py
visualization/eolearn/visualization/eoworkflow.py

The main idea is that in case we have multiple nodes with the same name they get shown in report as "name_1", "name_2", ... instead of "name", "name_1", ... Only in case a node name is unique it gets shown as "name".
I also fixed some types and improved unit tests.

Minor eoworkflow visualization update

---

CHANGELOG.md
features/eolearn/features/__init__.py
io/eolearn/io/__init__.py
setup.py

version 1.1.1

---

io/eolearn/io/geometry_io.py

A continuation of https://github.com/sentinel-hub/eo-learn/pull/432
This adds a filesystem support to the only vector IO task we have.

Added filesystem logic to VectorImportTask

---

core/eolearn/core/eoworkflow.py
core/eolearn/core/graph.py

part of the ongoing typization

Make the utility Graph class a generic

---

core/eolearn/core/eodata_io.py

In the refactoring of FeatureIO we lost the ability to read pickle files. This fixes it (for a while, since it will be removed soon).

Re-adds pickle reading to other data types

---

.github/workflows/ci_action.yml

Similar to https://github.com/sentinel-hub/sentinelhub-py/pull/326

Improve CI triggers

---

features/eolearn/features/feature_manipulation.py
features/eolearn/features/utils.py
features/eolearn/tests/test_feature_manipulation.py

Also refactored the way the parameters are passed to the task, breaking the existing API.

Adds an option to pass resolution to the SpatialResizeTask.

---

features/eolearn/tests/test_interpolation.py
io/eolearn/tests/test_sentinelhub_process.py

This (at least locally) shaves off about 10% of the test-suite time. We're not close to the 1min mark, but it's a start.

Make tests faster

---

core/eolearn/tests/test_core_tasks.py

Test checking deep copy of Map Feature Task

Add test for extract bands metod

---

core/eolearn/core/exceptions.py
core/eolearn/tests/test_exceptions.py
core/eolearn/tests/test_utils/test_raster.py

I checked codecov and identified two points which we don't test but probably should. So I fixed that.

Improve tests coverage of eolearn.core

---

core/eolearn/core/eodata_io.py
core/eolearn/tests/test_eodata_io.py

add sub class for handling timestamps
add test

FeatureIO for timestamp

---

core/eolearn/core/utils/parsing.py
docs/source/conf.py

Yeah, I hope'd we'd get away without doing it, and inside the module all is well. Outside it doesn't work, so I fixed it.

Docs using type aliases for features

---

io/eolearn/io/sentinelhub_process.py

Wont pass the tests until sh-py with the changes is released. Related sh-py PR is https://github.com/sentinel-hub/sentinelhub-py/pull/330

DRAFT: adjust to catalog 1.0.0

---

coregistration/eolearn/coregistration/coregistration.py

opencv sift were moved to their main repo

Fix coregistration register

---

docs/source/conf.py
features/eolearn/features/bands_extraction.py
features/eolearn/features/blob.py
features/eolearn/features/clustering.py
features/eolearn/features/feature_manipulation.py

Got tired of thinking about area managers and eopatch managers, so I did some cleaning

Add types and minor code refactors to half of eolearn.features

---

ml_tools/eolearn/ml_tools/sampling.py
ml_tools/eolearn/tests/test_sampling.py

Remove option to sample random integer points in triangle

---

.github/workflows/ci_action.yml
core/eolearn/core/eotask.py
core/eolearn/core/eoworkflow_tasks.py
features/eolearn/features/feature_manipulation.py
geometry/eolearn/geometry/morphology.py
geometry/eolearn/geometry/superpixel.py
geometry/eolearn/geometry/transformations.py
io/eolearn/io/sentinelhub_process.py
ml_tools/eolearn/ml_tools/sampling.py

1. adds `from __future__ import annotations` to all files using `FeaturesSpecification` so that it is correctly shortened in docs
2. adds types to all eolearn.geometry files
3. adds `py.typed` markers and enables typechecking in CI

Add types to eolearn.geometry

---

ml_tools/eolearn/ml_tools/sampling.py
ml_tools/eolearn/tests/test_sampling.py

refactor expand_to_grids, sample_by_values
add test for get_mask_of_samples
refactor the rest of the testsy

Refactor sampling

---

core/eolearn/tests/test_eodata.py

1. Refactored old test of `del`
2. Added some failure messages to test for copying + lazy loading
3. added tests for `get_spatial_dimensions`, `get_features` and `reset_feature_type`

Fix eodata tests

---

io/eolearn/io/geometry_io.py

add missing type annotations
update code 
remove unneeded docstring-s

Add types to geometry_io

---

io/eolearn/io/geopedia.py

add type annotations
updete code accordingly

Add type annotaions to geopedia

---

mask/eolearn/mask/cloud_mask.py
mask/eolearn/tests/test_cloud_mask.py

Changes:
- added types where relevant
- expanded on some names and made them more intuitive
- added comments here and there
- a bit larger refactoring of the `_update_batches`

Slight refactoring of the multitemporal cloud detection functions

---

mask/eolearn/mask/cloud_mask.py

Highlights a lot of problematic areas in the code.

Fix types in CloudMaskTask

---

core/eolearn/core/eodata_io.py

The refactorings are (or should be) entirely cosmetic.
I mostly extracted parts of code into helper functions, so that it is easier to see what happens when.
More refactoring will follow, but I want to keep it bite sized.

Refactor eodata_io (part 1)

---

core/eolearn/tests/test_core_tasks.py

+ fixture change from test_eopatch -> patch
+ add types
+ split test that test failing

Update extract and explode bands test

---

core/eolearn/core/utils/testing.py

Remove unused config parameter

Small fix related to a missing commit in #589

---

core/eolearn/core/eodata_io.py

This one focuses on getting rid of `walk_eopatch` as it is basically `FeatureParser(features).parse_features(eopatch)`

Yet another eodata_io refactor 

---

core/eolearn/core/core_tasks.py
core/eolearn/core/eodata.py
core/eolearn/tests/test_core_tasks.py
core/eolearn/tests/test_eodata.py

Also deprecate `reset_feature_type` because `del` does it better.

Prevent bbox deletion

---

examples/core/CoreOverview.ipynb
visualization/eolearn/visualization/eoexecutor.py

Did yall know we had a non-working core example notebook for a while? cause I didn't. But the EONode definitions were ill formed :joy:

Make sure that the examples use an explicit bbox

---

core/eolearn/core/constants.py
core/eolearn/core/eodata.py
core/eolearn/core/eodata_merge.py
core/eolearn/core/utils/parsing.py
core/eolearn/core/utils/testing.py
core/eolearn/tests/test_eodata.py
features/eolearn/features/feature_manipulation.py
io/eolearn/io/sentinelhub_process.py
visualization/eolearn/visualization/eopatch.py
visualization/eolearn/visualization/eopatch_base.py

first part of FeatureType cleanup

FeatureType cleanup

---

CREDITS.md
ml_tools/eolearn/ml_tools/tdigest.py

Type patch for TDigest task

---

.github/workflows/ci_action.yml
io/eolearn/tests/conftest.py

This is a minimal MR just to get our build up and running again.
Merged to master so that scheduled builds don't trigger for 3.7

Remove 3.7 from ci

---

io/eolearn/tests/conftest.py

Remove the config fixture from io tests

---

core/eolearn/core/eodata.py
core/eolearn/core/eodata_io.py
core/eolearn/core/utils/common.py
core/eolearn/tests/test_eodata.py
core/eolearn/tests/test_eodata_merge.py

The init got kinda messy, accepting ideas on how to clean it up
After this i would move the feature dict implementations under the EOPatch implementation, seems more intuitive for developers

Encapsulate FeatureDict as Mappings and do not inherit from dictionary

---

core/eolearn/core/constants.py
core/eolearn/core/eodata_io.py
core/eolearn/tests/test_eodata_io.py

sad that we need to copy-paste that meta-class (or complicate it to oblivion), but sometimes life is that way

Improve permissions and deprecate OVERWRITE_PATCH

---

core/eolearn/core/core_tasks.py

This way mypy can catch any `SaveTask(path, compresion_level=0)` typos. Also results in better docs.

Replace **kwargs with explicit parameters in IO tasks

---

.github/workflows/ci_action.yml

Use a conditional in CI to avoid --cov unless coverage is uploaded

---

core/eolearn/core/eodata.py
core/eolearn/core/eodata_io.py
core/eolearn/tests/test_eodata_io.py
core/eolearn/tests/test_eodata_merge.py

Adds partial loading from a temporal perspective.
We have yet to reach a consensus on what to do with vector data

Partial EOPatch loading

---

core/eolearn/core/core_tasks.py
core/eolearn/core/eodata.py
core/eolearn/core/eodata_io.py

I tried to start with the timestamp saving changes, but I noticed that core tasks have not yet been updated for partial IO. I also refactored how loading is done, so that timestamp loading changes will be easier

Refactor before timestamp save changes

---

coregistration/eolearn/coregistration/coregistration.py

I tested it out and the attribute does exist

Fix mypy complaining about cv2

---

core/eolearn/core/core_tasks.py
core/eolearn/tests/test_core_tasks.py
features/eolearn/features/interpolation.py
features/eolearn/tests/test_interpolation.py
geometry/eolearn/geometry/superpixel.py
geometry/eolearn/tests/conftest.py
geometry/eolearn/tests/test_superpixel.py

certain tasks were just slightly specialized base classes. No reason to have those.

Reduce number of tasks

---

mask/eolearn/mask/cloud_mask.py
mask/requirements.txt

Version restricted to <4
Types were adjusted since they were wrong.

Fix LGBM issues in build

---

core/eolearn/core/eoworkflow.py

Should make typing a bit easier in some eogrow pipelines

make type of `get_node_with_uid` reflect behaviour

---

.github/workflows/ci_action.yml
.gitlab-ci.yml

Had some issues that only occurred on mirroring, this should fix it (tried it by enabling mirroring of the branch)

Fix gitlab mirror CI

---

.github/workflows/ci_action.yml

We now need to explicitly state which module to watch

Fix codecov

---

eolearn/visualization/eoexecutor.py
eolearn/visualization/report_templates/report.html

Execution times are aggregated per-node and displayed
i also removed task sources since they dont serve much purpose
p.s. forgot the screenshot

Report execution times per node

---

docs/source/conf.py
eolearn/core/core_tasks.py
eolearn/features/extra/interpolation.py

Need to test it out on read-the-docs as well (sometimes it takes a while before you can enable a branch)

Make sure extra submodules are included when collecting list of tasks

---

README.md
eolearn/features/extra/__init__.py
eolearn/mask/extra/__init__.py
pyproject.toml

Underscores in extras are not allowed.

Merge separate extras into a single one

---

eolearn/features/extra/clustering.py
eolearn/geometry/morphology.py
tests/features/extra/test_clustering.py
tests/geometry/test_morphology.py

CV2 does not work with booleans, so this is a quick fix. The other task does not have such shortcomings due to the way it's constructed.
Had to adjust tests a bit because i was getting 15000 False values in 4 of the tests

Morphology on booleans

---

eolearn/core/utils/parallelize.py

Did some snooping, i think this module could be re-done to be less scattered and complex.
For now i only did some simplifications.

Small refactor of parallelization utils

---

.pre-commit-config.yaml
eolearn/core/constants.py
eolearn/core/core_tasks.py
eolearn/core/eodata.py
eolearn/core/eoexecution.py
eolearn/core/eotask.py
eolearn/features/extra/interpolation.py
eolearn/io/geometry_io.py
eolearn/io/raster_io.py
eolearn/visualization/eoexecutor.py
eolearn/visualization/eoworkflow.py
examples/core/CoreOverview.ipynb
examples/io/SentinelHubIO.ipynb
examples/water-monitor/WaterMonitorWorkflow.ipynb
pyproject.toml
tests/core/test_core_tasks.py
tests/core/test_eodata.py
tests/core/test_eodata_io.py
tests/core/test_eoexecutor.py
tests/core/test_extra/test_ray.py
tests/core/test_utils/test_common.py
tests/core/test_utils/test_parsing.py

Things inspired by yesterdays changes to sh-py

Minor revisions

---

eolearn/core/utils/parsing.py

New version of mypy found this issue

Fix type annotations in private parser method
