core/eolearn/core/eodata.py
core/eolearn/tests/test_eodata.py

Issue with overwriting EOPatch order.
In case of existing patch, a backup is created in case the saving fails. Backup is reinstated if this happens, otherwise discarded.
Additional small changes to npy default compression.

Bugfix/io EOpatch overwrite issue

---

features/eolearn/features/interpolation.py

Fixing the casting problem which results in interpolation problems on Windows machines. Rather simple fix. The problem was that the casting to float64 happened after the problem occurs on Windows, where the array overflows as int32, while on Linux/Unix it gets upcast automatically.
Perhaps some checks could be added to prevent if this occurs again in the future?

Windows interpolation fix

---

core/eolearn/core/eoworkflow.py

Naming EOTasks in EOWorkflow fails due to a bug in `_parse_dependencies` method. The loop has to be over parsed dependencies (`Dependency` objects and not tuples).

bug-fix: loop over a list of Dependecy objects instead of tuples.

---

core/eolearn/core/__init__.py
core/eolearn/core/core_tasks.py
core/eolearn/core/eodata.py
core/eolearn/tests/test_core_tasks.py

There is a usecase that I'm not sure whether it should be supported or not. One can duplicate multiple features as [('f1', 'f11'), ('f2', 'f21')], but not a single feature multiple times: [('f', 'f1'), ('f', 'f2')]. This case is also presented in test_core_tasks.py, but is commented out. As I understand, this is caused by the behavior of EOTask._parse_features, since it returns an ordered dict which would have feature_to_be_copied as a dict key and since dict keys cannot be repeated, the loop in DuplicateFeature doesn't go through the same feature_to_be_copied multiple times.

added DuplicateFeature to core tasks

---

core/eolearn/core/core_tasks.py
core/eolearn/tests/test_core_tasks.py

Because iteration over features happened on dictionary, one got `RuntimeError: dictionary changed size during iteration` when trying to run `RemoveFeature((FeatureType.MASK, ...))`

Fixes bug when user tried to remove all features of one type.

---

core/eolearn/core/core_tasks.py
core/eolearn/tests/test_core_tasks.py

For example, using ellipsis ... to indicate all features of certain type to be moved did not work. This is fixed now.

Fixes feature parsing in MoveTask. 

---

io/eolearn/io/sentinelhub_service.py
io/eolearn/tests/test_io.py

PR that adds an `orbit` parameter to the `S1IWWCSInput` and `S1IWWMSInput` tasks.
The parameter can have the following values:
* `'both'`: (_default_) images from both ascending and descending orbit are queried and downloaded;
* `'ascending'`: only images from ascending orbit direction are downloaded;
* `'descending'`: only images from descending orbit direction are downloaded.
Unit-tests are added for S1 WMS, WCS requests, as well as for WCS requests with ascending and descending images only.

Add orbit parameter to S1 input task

---

ml_tools/eolearn/ml_tools/train_test_split.py
ml_tools/eolearn/tests/test_train_split.py

Implemented 'per_value' splitting, where class ids get assigned to the same subclasses across multiple eopatches.

implemented 'per_value' train splitting

---

core/eolearn/core/eotask.py
core/eolearn/tests/test_eotask.py

EOTask execution wasn't working properly for exceptions that didn't have the expected __init__ signature (accepting only errmsg parameter). When such an exception occurred it wasn't clear where exactly it happened, because another exception was raised when trying to instantiate such an exception. I fixed it by avoiding instantiation of a new object through type(exception)(...) and instead I just change the errmsg of the existing exception object.

Bugfix: eotask execution exceptions

---

geometry/eolearn/geometry/transformations.py
geometry/eolearn/tests/test_transformations.py

This fix can be merged now. 
Later I intend to add `ImportFromVector` and `ExportToVector` tasks which will implement a better way of transforming imported dataframe to different CRS.

Enable VectorToRaster tranform crs on the fly with a warning

---

io/eolearn/io/local_io.py

When running with multiple workers enabled, it can happen that
the folder is created by  another worker between checking for
folder existence and creating new folder. **If **exists_ok** is set to **False**
the application will return an error.**
This fix changes the __get_file_path_ function so that it does not throw
and error if a folder that we are creating already exists.

Fix bug that occurs when checking/creating folders with multiple workers

---

io/eolearn/io/local_io.py
io/eolearn/tests/test_local_io.py

If the _ExportToTiff_ task is requested to create a map for a feature
that is not present in the EOPatch it will exit without an error and
log a warning message instead of exiting with an exception.
This is useful for workflows where we want to export multiple features
over a set of EOPatches. In the previous version the workflow would
fail and stop processing other features once it encountered one that
was not present in the EOPatch. This fix changes the behaviour so that
encountering a missing feature does not stop the execution for that
eopatch.

ExportToTiff now logs warning and finishes instead of failing.

---

io/eolearn/io/local_io.py
io/eolearn/tests/test_local_io.py

Reverts sentinel-hub/eo-learn#158

Revert "ExportToTiff now logs warning and finishes instead of failing."

---

CONTRIBUTING.md
README.md
requirements-docs.txt

Hi, it's my first time contributing to eo-learn, thus I think it was fitting to improve the contribution guide.
I have contributed to other open-source before, e.g. DVC and think their contribution guide (https://dvc.org/doc/user-guide/contributing) has some details the eo-learn guide is missing, for example, the guide of setting up a virtual Python environment for development which I have documented in this pull request.
A guide for executing the unittests could also be useful. However, I'm not familiar enough with your test setup to document such a guide. Are somebody else up for that?

Added development environment guide to CONTRIBUTING.md

---

core/eolearn/core/eoexecution.py

A minor fix on multiprocessing lock. The previous version of the code prevented running eo-learn with `dask.distributed`.

fix in case multiprocessing lock cannot be initialized

---

io/eolearn/io/processing_api.py

Sentinel-hub service has recently been updated and now `eo-learn`'s Processing API requests fail, because they didn't include evalscript version.
In this PR, evalscript version is added.

Bugfix: added evalscript version

---

core/eolearn/core/core_tasks.py

Corrected function calls in Docstrings of functions `MapFeatureTask` and `ZipFeatureTask`. Previously `multiply` function was called where it should have been `maximum` and `calc` wherever required.

Correct function call in Docstrings

---

core/eolearn/core/eoexecution.py
core/eolearn/core/utilities.py

In case each execution in `EOExecutor` spawns sub-threads then logs in those sub-threads were not being recorded. This PR disables the log filter in case of multi-processing or single-threaded execution.
In case of multi-threaded execution, there has to be a filter that prevents recording logs from other threads. However, I don't see an efficient way of how not to filter logs from any possible sub-threads.

in multiprocessing case logs are not filtered by a thread

---

.travis.yml
CHANGELOG.md
core/eolearn/core/__init__.py
core/requirements.txt
geometry/eolearn/geometry/__init__.py
geometry/eolearn/geometry/transformations.py
geometry/setup.py
io/eolearn/io/__init__.py
io/eolearn/io/geopedia.py
io/eolearn/io/processing_api.py
io/setup.py
setup.py

Prerequisite for this PR is this [sentinelhub-py PR](https://github.com/sentinel-hub/sentinelhub-py/pull/107)

Use the SentinelHubRequest for issuing Processing API requests

---

core/eolearn/core/eoworkflow.py
core/eolearn/tests/test_eoworkflow.py
io/eolearn/io/processing_api.py

Fixes 'Instance ID is not set.' when using SentinelHubInputTask without having global config.json set up
Minimal (non-working) example:
On fresh install of eolearn (e.g. pip install eo-learn), without setting up config.json with all parameters, it should be possible to use processing api with code like this:
```python
import datetime
from eolearn.core import FeatureType
from eolearn.io import SentinelHubInputTask
from sentinelhub import CRS, BBox, DataSource, SHConfig
if __name__ == '__main__':
bbox = BBox(bbox=[268892, 4624365, 269892, 4625365], crs=CRS.UTM_33N)
time_interval = ('2017-12-15', '2018-1-30')
config = SHConfig()
config.sh_client_id = '...'
config.sh_client_secret = '...'
config.instance_id = '...'
task = SentinelHubInputTask(
size=(100, 100),
bands_feature=(FeatureType.DATA, …
```

Bug with processing Api and no global config.json set up

---

features/eolearn/tests/test_interpolation.py

This PR adds a unit-test in the interpolation module for the `interpolate_pixel_wise` flag. This seemed to be an issue raised in #125.
The tests pass with no code changes, so possibly the data used in issue was in wrong format?

Add test for pixel-wise interpolation

---

features/eolearn/features/feature_manipulation.py
features/eolearn/tests/test_feature_manipulation.py
requirements-dev.txt

[This line](https://github.com/sentinel-hub/eo-learn/commit/4ad7bba060825c1047095885d420e296a5772e09#diff-43f01a19420680c6833c66a1a7366d22R165) in `ValueFilloutTask` contains a typo (the axis is wrong and `1` is added instead of subtracted), which causes problems in fillout in the backward direction. The result of chaining forward and backward fillout may also be corrupted by the latter operation.
The tests are a bit unfortunate in the sense that they all end up testing the function on data of the same particular form, which happens to work - specifically, where only the first element per row needs to be filled out, e.g.:
```python
>>> fill(np.array([[np.nan, 68., 62, 99., 67., 92., 22., 80.]]), operation='b')
array([[68., 68., 62., 99., 67., 92., 22., 80.]])  # Working as expected
``` …

Fixed value fillout bug

---

core/eolearn/core/core_tasks.py
core/eolearn/core/eodata_io.py
core/eolearn/core/fs_utils.py
core/eolearn/tests/test_fs_utils.py
io/eolearn/io/local_io.py
io/eolearn/tests/test_local_io.py

This feature enables using both tasks to load data from s3 by simply specifying `folder='s3://my-bucket/path'`.
Additionally, I have also added a few minor filesystem-related improvements in the core subpackage.

Filesystem support for ExportToTiff and ImportFromTiff tasks

---

io/eolearn/io/local_io.py
io/eolearn/tests/test_local_io.py

As follow-up to [https://github.com/sentinel-hub/eo-learn/pull/257](https://github.com/sentinel-hub/eo-learn/pull/257), extending the functionality of `ImportFromTiff` in order to build time-dependent features from a list of filenames.
For this use case, I am expanding on the usage of `*` or `strftime` for `ImportFromTiff`, which creates a hypothetical list of files and checks for their existence before attempting to open them.
A custom file list can also be passed with (import into existing `EOPatch`) or without (create a new `EOPatch`) timestamps. 
If the former, the length of the file list provided should match the number of timestamps of the existing EOPatch.
If the latter, the timestamps should be assigned by the user outside of the `ImportFromTiff` method, as there is no effective …

Possibility to create time-dependent feature from a list of filenames

---

coregistration/eolearn/coregistration/coregistration.py
coregistration/eolearn/tests/test_coregistration.py

- a bug was discovered in the coregistration where the warp matrix used has not been inverted in order to correct for the misalignments, causing them to increase instead of fixing them
- additionally, the algorithm was improved by calculating the coregistration matrix from the normalized gradients of the input images
- ~~the reference image has been set to be the last frame~~
Very weird effect
Also weird effect, probably due to the changing reference, where the reference itself was affected with the bug
The last frame was used as a reference and it was not altered at all, you can see the effects of increased misalignments, which  points into the direction of a non-inverted matrix
Everything is OK after the matrix has been inverted

Fix and improve coregistration

---

examples/land-cover-map/.gitignore

Made a few improvements to the example notebook, mainly:
- changes to satisfy PEP8 guidelines
- directory paths are now specified at the start and not over multiple cells
- longer variable names to improve readability
- fixed `numpy` deprecation warnings and an issue with dates

Clean up LULC example notebook

---

core/eolearn/core/fs_utils.py

Tests passing on Windows:
* relative paths using both Unix and WIndows syntax:
*  `.\\test-folder`
*  `./test-folder`
* absolute paths using Windows syntax, script on C drive :
*  `C:\\Users\\pippo\\test-folder`  
*  `H:\\test-folder`
Is there any other possibility that should be covered, that I am not aware of?

windows fix absolute paths

---

core/eolearn/core/core_tasks.py

The example in the description of `MapFeatureTask` incorrectly states that `map_function` has to be implemented when it should be `map_method`.

Fix mistake in description of MapFeatureTask

---

io/eolearn/io/geometry_io.py
io/eolearn/tests/test_geometry_io.py

geodb supports more `comparison_mode`s as advertised in docs.
The default for the ImportVectorTask should have been  'intersects', which this PR resolves.

comparison_modes 

---

io/eolearn/io/local_io.py

I have been trying to load Landsat-8 data to EOPatch and find out that EO-learn is not able to load GeoTiff files with extension in uppercase, e.g:
```
BC/LC80500092014231LGN00/LC80500092014231LGN00_B9.TIF
```
```
$ cp ./example_data/import-tiff-test2.tiff ./example_data/import-tiff-test3.TIF
```
and then loading in interactive python shell results in something like this:
```python
Python 3.8.8 (v3.8.8:024d8058b0, Feb 19 2021, 08:48:17) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from eolearn.io import ExportToTiff, ImportFromTiff
>>> from eolearn.core import EOPatch, FeatureType, MergeFeatureTask
>>> task_load = ImportFromTiff((FeatureType.DATA_TIMELESS, 'DATA'))
>>> eo_patch = …
```

ImportFromTiff task is now able to load tiff files with uppercase extension

---

core/eolearn/core/eodata_io.py
core/eolearn/tests/test_eodata_io.py

Saving eopatch features at different compression levels produces an issue with old files not being properly overwritten (due to the added `.gz` file suffix). This leads to duplication of files as well as possible bugs when loading features.
This is now fixed with an additional step, where such files are found and removed (after the new ones are saved).

Fix eopatch saving w.r.t. compression and lazy loading

---

core/eolearn/core/__init__.py
core/eolearn/core/core_tasks.py
core/eolearn/core/utilities.py
core/eolearn/tests/test_core_tasks.py
core/eolearn/tests/test_eoexecutor.py
coregistration/eolearn/coregistration/__init__.py
coregistration/eolearn/coregistration/coregistration.py
coregistration/eolearn/tests/test_coregistration.py
features/eolearn/features/__init__.py
features/eolearn/features/feature_manipulation.py
features/eolearn/features/interpolation.py
features/eolearn/features/radiometric_normalization.py
features/eolearn/tests/test_feature_manipulation.py
features/eolearn/tests/test_interpolation.py
features/eolearn/tests/test_radiometric_normalization.py
geometry/eolearn/geometry/__init__.py
geometry/eolearn/geometry/superpixel.py
geometry/eolearn/geometry/transformations.py
geometry/eolearn/tests/test_superpixel.py
geometry/eolearn/tests/test_transformations.py
io/eolearn/io/__init__.py
io/eolearn/io/geopedia.py
io/eolearn/io/local_io.py
io/eolearn/io/sentinelhub_process.py
io/eolearn/tests/test_local_io.py
mask/eolearn/mask/__init__.py
mask/eolearn/mask/masking.py
mask/eolearn/mask/snow_mask.py
mask/eolearn/tests/test_masking.py
mask/eolearn/tests/test_snow_mask.py

Most tasks in `eolearn` follow the naming convention of the `Task` suffix. This PR ensures the naming convention is followed in the remaining tasks, while keeping the old versions with a deprecation warning.

Ensure naming convention for tasks

---

core/eolearn/core/eodata.py
core/eolearn/core/eoworkflow.py
core/eolearn/tests/test_eodata.py

Before each task in an EOWorkflow is executed the workflow will make sure that all input EOPatches are shallow-copied. This ensures the correct logic in a complicated workflow. This PR also adds `EOPatch.copy` method.
Tests for checking the copy functionality of EOWorkflow will be added in another PR into develop-v1.0.

EOWorkflow makes shallow copies of EOPatches

---

core/eolearn/core/eodata.py
core/eolearn/tests/test_eodata.py

Add support for `del eopatch[(feature_type, feature_name)]`.
Works in the same way as `del eopatch[feature_type][feature_name]`.

Add `__delitem__` method

---

examples/mask/ValidDataMask.ipynb
examples/water-monitor/WaterMonitorWorkflow.ipynb

Minimal updates just to get the notebooks to work without any kind of deprecation errors.
I marked it as a draft, because if we add new sampling methods, the LULC pipeline notebook needs to be updated again.

Update example notebooks that appear in docs

---

io/eolearn/io/sentinelhub_process.py
io/eolearn/tests/test_sentinelhub_process.py

Sentinel Hub Service recently changes the units of the Landsat collections. This makes `SentinelHubInputTask` unusable for Landsat collections (as seen [here](https://github.com/sentinel-hub/sentinelhub-py/issues/209)).
This is a temporary fix (since a proper fix requires large changes to sentinelhub-py) that manually changes the types used when a landasat collection is selected.
Also fixes a pycodestyle error (line 414) that has bothered me for a while.

Add a temporary fix for LANDSAT collections

---

io/eolearn/io/sentinelhub_process.py

Apparently adding a comment to ignore that line worked for my local pylint but didn't work for CI

Remove remaining .format to satisfy pylint

---

io/eolearn/io/sentinelhub_process.py

In some cases `None` was assigned as the value of the timestamp, where `[]` should have been used instead.
Also a minor code-style fix

Remove None as possible timestamp

---

core/eolearn/core/eodata_merge.py
core/eolearn/tests/test_eodata_merge.py

In the current implementation the merge functions use direct `get` access in a feature dict, bypassing the mechanisms for loading features. This can be fixed by restructuring the control flow just a bit.

Make merge functionality work with lazy loading

---

core/eolearn/core/fs_utils.py
core/eolearn/tests/test_fs_utils.py

A minor PR to support loading AWS credentials from profile. 
So far I haven't added any unit test for this as it would be a bit tricky. I might have to mock `boto3.Session` object or something like that. Let me know if you think we need a test for this.

Support for aws_profile parameter

---

features/eolearn/features/feature_manipulation.py
features/eolearn/tests/test_feature_manipulation.py
io/eolearn/io/sentinelhub_process.py

With these changes only SH input tasks add meta_info information and even these make sure that all meta_info content is JSON serializable.

Update meta_info handling to ensure serialization

---

core/eolearn/core/__init__.py
core/eolearn/core/eoexecution.py
core/eolearn/core/eonode.py
core/eolearn/core/eotask.py
core/eolearn/core/eoworkflow.py
core/eolearn/core/eoworkflow_tasks.py
core/eolearn/core/graph.py
core/eolearn/core/utilities.py
core/eolearn/tests/test_eoexecutor.py
core/eolearn/tests/test_eonode.py
core/eolearn/tests/test_eotask.py
core/eolearn/tests/test_eoworkflow.py
core/eolearn/tests/test_eoworkflow_tasks.py
core/eolearn/tests/test_graph.py
core/eolearn/tests/test_rayexecutor.py
visualization/eolearn/tests/test_eoexecutor_visualization.py
visualization/eolearn/tests/test_eoworkflow_visualization.py
visualization/eolearn/visualization/eoexecutor_visualization.py
visualization/eolearn/visualization/eoworkflow_visualization.py

This introduces a very code-breaking change, but strengthens the foundations of eo-learn.
EOWorkflows are no longer built directly from tasks, but now require EONodes, which contain tasks and describe the graph structure of the workflow.

Introduce EONodes as EOWorkflow building blocks

---

geometry/eolearn/geometry/transformations.py
geometry/eolearn/tests/test_transformations.py

Fixes the issue with Shapely 1.8 removing the `to_wkt` method we used to project 3D -> 2D in rasterization task.

Update code for projecting to 2D in rasterization

---

core/eolearn/core/eoexecution.py
core/eolearn/core/eonode.py
core/eolearn/core/eotask.py
core/eolearn/core/eoworkflow.py
core/eolearn/core/extra/ray.py
core/eolearn/tests/test_eoexecutor.py
core/eolearn/tests/test_eotask.py
core/eolearn/tests/test_eoworkflow.py
core/eolearn/tests/test_rayexecutor.py
visualization/eolearn/visualization/eoexecutor_visualization.py
visualization/eolearn/visualization/report_templates/report.html

This is the first part of the improvements planned for `EOExecutor`. This one makes updates related to changes in `EOWorkflow` structure:
- `WorkflowResults` are now always returned for each workflow execution,
- error handling now happens in `EOWorkflow` and not in `EOExecutor` and `EOTask`,
- logs report error stack trace,
- avoiding memory leaks by preventing `EOExecutor` to keep `EOWorkflow` outputs, ...
The next part will be mostly about improving `EOExecutor` itself and its report.

EOExecutor improvements, part 1

---

core/eolearn/core/utilities.py

This solves type annotations without introducing a circular import. A tiny bit ugly but apparently the go-to approach

Fix type annotations in FeatureParser

---

core/eolearn/core/eoexecution.py
core/eolearn/core/eonode.py
core/eolearn/core/extra/ray.py
core/eolearn/core/fs_utils.py
core/eolearn/tests/test_eoexecutor.py
core/eolearn/tests/test_fs_utils.py
core/eolearn/tests/test_rayexecutor.py
examples/core/CoreOverview.ipynb
visualization/eolearn/tests/test_eoexecutor_visualization.py
visualization/eolearn/visualization/eoexecutor_visualization.py
visualization/eolearn/visualization/report_templates/report.html

Implements various improvements in `EOExecutor` class and especially in the generated report. Changes are documented in commit messages.

EOExecutor improvements, part 3

---

core/eolearn/core/__init__.py
core/eolearn/core/core_tasks.py
coregistration/eolearn/coregistration/__init__.py
coregistration/eolearn/coregistration/coregistration.py
features/eolearn/features/__init__.py
features/eolearn/features/feature_manipulation.py
features/eolearn/features/interpolation.py
features/eolearn/features/radiometric_normalization.py
geometry/eolearn/geometry/__init__.py
geometry/eolearn/geometry/superpixel.py
geometry/eolearn/geometry/transformations.py
io/eolearn/io/__init__.py
io/eolearn/io/geopedia.py
io/eolearn/io/local_io.py
mask/eolearn/mask/__init__.py
mask/eolearn/mask/masking.py
mask/eolearn/mask/snow_mask.py

This is the perfect moment to remove the old names of tasks (before we started enforcing the `Task` suffix for our tasks).

Remove deprecated task names

---

docs/source/conf.py
requirements-docs.txt

Same trick as we started to use in `sentinelhub-py`.

Docs build fix - mocking problematic imports

---

core/eolearn/core/extra/ray.py

The previous version updated the progress bar one by one. However each time ray had to check entire list of futures. This caused MASSIVE slowdowns when working with many eopatches (300k), because the progress bar updating took >6h by itself.
It has now been improved to only check every now and then, but updates the bar for all futures that are done (and not just the next one). Works with large amount of eopatches and does not delay very fast executions. Updating is a bit less continuous but it's a small price.

progress bar for ray now works for large number of eopatches.

---

core/eolearn/core/core_tasks.py
core/eolearn/tests/test_core_tasks.py
requirements-dev.txt

This adds an option that by setting `eopatch_folder=None` these 2 task won't save or load anything. This way we can use execution arguments to handle cases where we know that no data exists to be loaded or no data needs to be saved.

Option that LoadTask and SaveTask don't do anything

---

core/eolearn/core/eodata_io.py

The latest version `fs==2.4.16` introduced an issue that is described in https://github.com/PyFilesystem/pyfilesystem2/issues/535. 
It seems very likely that the issue will be fixed in the next version of `fs` package release. Therefore this PR only patches the issue for this specific `fs` version. The additional check happens only when saving EOPatches locally but in order to conserve the amount of unnecessary IO operations I wouldn't call it for other `fs` versions because it is unnecessary.

Patched issue with saving existing EOPatch features locally

---

core/eolearn/core/eodata_io.py
core/eolearn/core/eoexecution.py
core/eolearn/core/utils/common.py
core/eolearn/core/utils/fs.py
core/eolearn/tests/test_utils/test_common.py

I extended `is_discrete_type` function so that it works both with `type` and `numpy.dtype` objects (because `numpy` also works with both). Then I wrote precise unit tests for it.
More info about type hierarchy can be found in [`numpy` docs](https://numpy.org/doc/stable/reference/arrays.scalars.html).

Extended is_discrete_type function and wrote unit tests for it

---

geometry/eolearn/geometry/transformations.py

If the vector data is passed a string (e.g. path to a vector file), then the 'TIMESTAMP' column is an `object` instead of `datetime`. 
This PR reads the `TIMESTAMP` column into a pandas `datetime64` dtype, using `parse_time` from sentinelhub-py so that the resulting timestamps are created using the same procedure as the `timestamp` list in eo-patches.
A side note: in `FeatureIO`, in `_decode` method, the `TIMESTAMP` column (if exists) is parsed with `dataframe.TIMESTAMP = pd.to_datetime(dataframe.TIMESTAMP)`. I suggest to replace it with `dataframe.TIMESTAMP = pd.TIMESTAMP.apply(parse_time)` - again, to conform to the `timestamp` feature in eo-patches.

VectorToRaster task for temporal vector features

---

core/eolearn/core/__init__.py
core/eolearn/core/eoexecution.py
core/eolearn/core/extra/ray.py
core/eolearn/core/utils/parallelize.py
core/eolearn/tests/test_extra/test_ray.py
core/eolearn/tests/test_utils/test_parallelize.py
docs/source/eolearn.core.rst
docs/source/eolearn.core.utils.parallelize.rst

The code that deals with parallelization has been extracted from `EOExecutor` and `RayExecutor`, transformed into useful utility functions, and generalized. What I was able to achieve:
- Utility functions are ordered from a high level to low level, because different use cases require different levels of customization. Functions for users are:
* `parallelize` and `parallelize_with_ray`,
* `join_futures` and `join_ray_futures`,
* `join_futures_iter` and `join_ray_futures_iter`
In general I think these names make sense but feel free to add other suggestions.
- On a low level, the PR implements this functionality of early removal of finished future objects. This can be achieved only if there are no other references to future objects in the runtime which means we also have to remove them from …

Parallelization utils

---

core/eolearn/core/eonode.py
core/eolearn/tests/test_eonode.py

Because EONode is a frozen dataclass the built-in hashing is done via structural recursion (apparently in a non-memoized way). The slowdown seems to be exponential and in workflows with over 120 nodes the time required becomes an enormous issue.
Since we use EONodes as keys in execution arguments (and in `from_endnodes` and possible elsewhere) this needs to be improved.
The suggested improvement instead hashes the EONodes uid, for which we already assume it's unique (and is often used as a key internally).

Faster node hash

---

core/eolearn/core/core_tasks.py
core/eolearn/tests/test_core_tasks.py

I believe this to be a good addition because it allows loading from multiple folders in a linear (sub)workflow. This allows more control over execution order and also simplifies certain workflows (no need for an explicit merge task).
If you feel like this functionality is not desired I would remove it, but keep part of the tests, since they are related to the LoadTask as it is.

Add optional input to Load task

---

coregistration/eolearn/tests/test_coregistration.py
geometry/eolearn/tests/test_transformations.py
io/eolearn/tests/conftest.py
io/eolearn/tests/test_local_io.py
requirements-dev.txt

- In `pytest>=7.0.0` a parameter of `pytest.skip` was renamed - this fixes it.
- Tests now make sure that EO warnings are being raised wherever expected and not raised otherwise.
These updates reduced a bit the number of warnings we get in tests. We still get a ton of warnings because of an issue in `geopandas` that will be fixed in the next `geopandas` version. We also get quite a number of warnings because a utility function in core intentionally tests deprecated numpy types.

Minor pytest updates

---

features/eolearn/features/feature_manipulation.py
features/requirements.txt

- Dtype is now being parsed already in `__init__`.
- It turned out I had to upgrade Pillow to `>=9.0.0` because lower versions didn't have `PIL.Image.Resampling`.

Linear function dtype update

---

features/requirements.txt
io/eolearn/io/local_io.py
io/eolearn/tests/test_local_io.py

In PR https://github.com/sentinel-hub/eo-learn/pull/416 I introduced a bug. In case input EOPatch didn't have a bounding box  `ImportFromTiffTask` should set a bounding box from the image to it. In the refactoring I forgot about this.
This is now fixed and I also added checks in tests that verify this.

Fixed BBox setting in ImportFromTiffTask

---

core/eolearn/core/eodata_io.py
core/eolearn/core/utils/common.py
core/eolearn/tests/test_utils/test_common.py

It turned out that `gdf.to_file` method even in the older `geopandas` version could under some conditions also save index as a new column. Now that saving empty dataframes started to work in `0.11.0` such a condition was met and only in case of empty dataframes it was saving with an unnecessary `index` column. This shouldn't be a big problem for users but our tests reported that a sequence of save and load operation doesn't produce exactly the same results.
Changes:
- Prevented saving index column and suppressed a warning about saving an empty dataframe.
- Also suppressed warnings that were emitted by tests of `is_discrete_type` utility function. Now `eolearn.core` tests are free of warnings.

Fixed compatibility with geopandas 0.11.0 and suppressed all warnings in eolearn.core

---

core/eolearn/core/core_tasks.py
core/eolearn/core/utils/fs.py
core/eolearn/tests/test_core_tasks.py
core/eolearn/tests/test_utils/test_fs.py

The main use case for this is that we'll be able to first define a filesystem object with all parameters (e.g. credentials, ACL settings, ... ) and then pass it as an init parameter to IO tasks. This was solved by custom pickling and unpickling functions for filesystem objects.
Notes: 
- we still have to update IO tasks from `eolearn.io` subpackage. This will be done in next PRs.
- CI is still failing but only because of an unrelated `rasterio` issue.

Filesystem upgrade and serialization

---

core/eolearn/tests/conftest.py
core/eolearn/tests/test_eodata_io.py
core/eolearn/tests/test_utils/test_fs.py
requirements-dev.txt

Changes:
- Added a test that makes sure `S3FS` is fully usable after being unpickled.
- Reduced code duplication by using a package `pytest-lazy-fixture`. If this works well I think we have a few more cases where such solution would be great.

Extra S3 filesystem pickling test

---

core/eolearn/core/eoexecution.py
core/eolearn/tests/test_eoexecutor.py
core/requirements.txt

This should be the last PR in the series of filesystem-handling changes. It is about passing a filesystem object to log handlers of each workflow execution.

Updated logs_handler_factory parameter to support filesystem changes

---

io/eolearn/io/sentinelhub_process.py
io/eolearn/tests/test_sentinelhub_process.py
io/requirements.txt

Just a minor update because it bothered me that in `eogrow.pipeline.download` PyCharm was showing a mismatched type for this parameter.

Handling of MosaickingOrder in SH input tasks

---

features/eolearn/features/feature_manipulation.py
features/eolearn/tests/test_feature_manipulation.py

There are a few minor changes in the functionality:
- In case all timestamps are filtered the old version raised an error but the new version returns empty numpy arrays (i.e. shape (0, height, width, bands)) and empty GeoDataFrames.
- The new version returns a shallow copy of an input EOPatch. That is because otherwise we would have a mismatch in time dimension.
- I removed `_update_other_data` method because it was useless. Instead, any such update can be performed in a separate task.
- The new version now also supports filtering vector features.
Note: I'm not sure if I correctly handled type of `filter_func` but it is a bit tricky because it depends on feature type of `feature` parameter.

Updated SimpleFilterTask and wrote additional unit tests

---

core/eolearn/core/eodata_io.py

FeatureIO seemed to be a 'swiss army knife' class, so I extracted the common behaviour into a generic class that is then specialized in subclasses. This also greatly improves type information. Sadly we currently cannot 100% guarantee type safety for JSON-like data (so timestamp and metainfo) and geodataframes (due to deprecated pickle functionality). I am considering further specializing json-like featureIO into specific ones for timestamps and metainfo, but it might cause some code duplication, since both are handled very similarly. Open to ideas.

separate FeatureIO into subclasses

---

core/eolearn/core/eodata.py

Similar to `FeatureIO` the only proper way to bring some notion of types to `EOPatches` begins at making a generic `_FeatureDict` which is then properly sub-classed. Now `eopatch.data["name"]` is recognized as a numpy array. Can't do much about `eopatch[FeatureType.DATA, "name"]` without a massive amount of overloads.

Typed feature dicts

---

.readthedocs.yml
docs/source/conf.py

The process now explicitly copies the image for the core overview notebook.
Read-the-docs started crashing due to conda being too slow (over 300 seconds to build the env :scream_cat: ) so as suggested by ReadTheDocs I switched over to using Mamba. This moves the python version of docbuilding from 3.7 to a special mamba 3.10, but it now takes 200s to build the env and the docs seem the same.

Fix image in core example notebook

---

io/eolearn/io/extra/meteoblue.py
io/eolearn/tests/test_extra/test_meteoblue.py

MeteoblueRasterTask was previously using northward facing y-axis in contrast to data coming from sentinelhub

fix: meteoblue y-axis orientation for MeteoblueRasterTask

---

features/eolearn/features/feature_manipulation.py

Slight modification to the FilterTimeSeriesTask to enable its use with parallel Executor. Unchanged otherwise. The lambda function in the class' previous version prevented it from being pickled
Fixes bug #446

fix FilterTimeSeriesTask for use with parallel executor

---

visualization/eolearn/visualization/eopatch.py

No test (it is hard to make test for this) we make manual test using notebook:

Make default ploting in EOPatch be without interpolation

---

docs/environment.yml
docs/source/conf.py
requirements-docs.txt

Same solution as for `sentinelhub-py` in https://github.com/sentinel-hub/sentinelhub-py/pull/316
You can check the newly built docs [here](https://eo-learn.readthedocs.io/en/docs-github-url/).

Fixed GitHub URL links in documentation

---

core/eolearn/core/eodata.py
core/eolearn/core/eodata_io.py

When designing the tests it came up that `FeatureIO` cannot load it's own saved file, due to the inconsistencies with paths.
On saving the object assumed paths returned by `walk_eopatch` which are just a file-system-structured paths of features (e.g. `"eopatch/data/NDVI"`) and lack any extensions.
On loading the object assumed filesystem paths (e.g. `"eopatch/data/NDVI.npy.gz"`).
Turns out it is not that simple to unify the two. What I did is:
- paths are always assumed to be filesystem paths with full extensions
- they are checked for compliance with feature type extension and compression level
- if the compression level is not specified, it is inferred from path (so 0 if no `.gz` ending and 1 otherwise), which is needed for loading, since we have no clue how the feature was saved other …

Avoid inconsistency in paths of FeatureIO

---

core/eolearn/tests/test_eodata_io.py

Tests verifying that FeatureIO subclasses correctly save, load, and lazy-load data. Test cases do not include subfolders, because subfolder management is currently done by the `save_eopatch` function.

Add Feature io test

---

core/eolearn/core/eodata_io.py
core/eolearn/tests/test_eodata_io.py

In some rare cases users want to save and load arrays populated with objects, which are serialized with pickle. Numpy does not allow loading of such data by default since pickled objects are a security issue. This MR removes this restriction.

Allow loading numpy arrays containing objects

---

core/eolearn/core/eodata.py
core/eolearn/core/eodata_merge.py

Adds annotations to all EOPatch methods. Accessing via keys is still not as strong as one would've hoped, but even so it can do certain checks such as:
```python
test_eopatch = EOPatch()
_ = test_eopatch["something"]  # marked as wrong access
_ = test_eopatch[(FeatureType.DATA, 3)]  # marked as wrong access
_ = test_eopatch[(FeatureType.BBOX, ...)]  # works
test_eopatch["something"] = 1  # marked as wrong access
test_eopatch[(FeatureType.DATA, 3)] = None  # marked as wrong access
test_eopatch[(FeatureType.DATA, "something")] = None  # marked as correct, doesn't know the appropriate types
bbox = test_eopatch[FeatureType.BBOX]  # type is BBox
timestamp = test_eopatch[(FeatureType.TIMESTAMP, None)]  # type is List[dt.datetime]
data1 = test_eopatch[FeatureType.DATA]  # type is Any :(
data2 = …
```

Add types to EOPatch

---

core/eolearn/core/core_tasks.py
core/eolearn/tests/test_core_tasks.py

might be useful in some cases
in EOGrow we might need to do Batch2EOPatch with the option to specify axis, and this is a necessary first step for it

Add axis parameter to MergeFeatureTask

---

io/eolearn/io/sentinelhub_process.py
io/eolearn/tests/test_sentinelhub_process.py

Closes https://github.com/sentinel-hub/eo-learn/issues/498
@ColinMoldenhauer is this sufficient for your needs? I would also like to add you as a [co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) (since the idea and solution suggestion are yours), but I'd need an e-mail under which to add you.

Add custom timestamp filtration

---

docs/environment.yml

Somewhere along the way either the default python version changed, or numba started complaining about 3.11
This sets our docsbuilding python to 3.10 to avoid issues

Fix docs by settings python to 3.10

---

.flake8

Nothing to be 'fixed' found, cannot do the `!r` flag because we still support python 3.7

skip B028 for flake8

---

core/eolearn/core/core_tasks.py
core/eolearn/core/eodata.py
core/eolearn/tests/test_core_tasks.py
core/eolearn/tests/test_eoworkflow_tasks.py
features/eolearn/features/interpolation.py

1. `get_features_list` and `get_features` have been joined into a new `get_features` that returns a list as if the parser were run on the EOPatch (no more weird types)
2. the `get_timeseries` had little to do with the EOPatch, so it was moved to the only place where it was used, interpolation tasks

Reduce `EOPatch` method count

---

features/eolearn/features/feature_manipulation.py
features/eolearn/tests/test_feature_manipulation.py

Changes that were made: 
* The signature of the SpatialResizeTask was changed to explicitly take width / height parameters. 
* The bug that switched the width/height when using resolution was fixed 
* Tests were updated to reflect the new signature, tests were added to test for non-symettbic width/height parameters for `ResizeType.SCALE_FACTORS` and `ResizeType.RESOLUTION`

Fixes SpatialResizeTask that switched width/height when using resolution

---

core/eolearn/core/eodata.py
core/eolearn/tests/test_eodata.py

While we will move away from BBOX and TIMESTAMP feature types, for the time being it seems right to support deletion of those as well. I did make it so that one must use their full spec (so `(FeatureType.BBOX, None)`) in order to not lose too much time with it

Add delete instructions for bbox and timestamps

---

io/eolearn/io/geometry_io.py
mask/eolearn/mask/snow_mask.py

add type annotations to snow_mask
add type annotations to geometry_io

Add missing type annotations

---

core/eolearn/core/eodata.py
core/eolearn/tests/test_core_tasks.py

Since the BBox is the spatial definition of the EOPatch it should always be copied.

Copying always copies the BBox

---

core/eolearn/core/eodata_io.py

Switches return type of `walk_filesystem` to simplify a lot of the logic. Many changes were made to make it harder to screw up in the future.

Refactor eodata_io

---

core/eolearn/core/eodata.py

The dunder methods were using non-standard names for parameters, which bothered me a bit.
The `_check_tuple_key` method was awkward so i inlined parsing and it produces nicer code.
I added a descriptor comment on why `contains` has such a broad type (makes me sad)
Also i am 99% sure that `get_spatial_dimension` was just plain bullshit before.

Streamline EOPatch dunder methods and some small corrections

---

core/eolearn/core/eodata_io.py
core/eolearn/tests/test_eodata_io.py

in one of the refactoring PRs we made breaking changes to the `walk_filesystem` functionality. This is now updated so that `eo-grow` tests that use this functionality don't fail with `develop` version of `eo-learn`.
Changes:
- renamed refactored function
- added interface for old function
- added tests

Add interface to the old walk_filesystem function for backward compatibility

---

core/eolearn/core/eodata.py
core/eolearn/tests/pytest.ini
core/eolearn/tests/test_core_tasks.py
core/eolearn/tests/test_eodata.py
core/eolearn/tests/test_eodata_merge.py
core/eolearn/tests/test_eoworkflow.py
features/eolearn/tests/test_feature_manipulation.py
features/eolearn/tests/test_temporal_features.py
io/requirements.txt
requirements-dev.txt
visualization/requirements.txt

Sorry, sorry, i know, i did a lot of changes that are not 100% related:
1. Added deprecation warning to init and to setter, added test for it
2. Removed pytest.ini because it was messing with warnings depending on which folder you called `pytest` from
3. Adjusted tests so that the warnings from point 1. is not triggered
4. Adjusted a test for zip task, because it raised a warning about dividing by zero
5. cleaned up requirements :see_no_evil:

Add deprecation warning to EOPatches without a BBox

---

.zenodo.json
CREDITS.md

My contributions to eo-learn were developed as part of a TUM project, hence I would appreciate if the affiliation could be added.

Add affiliation Moldenhauer

---

.flake8
io/eolearn/io/geometry_io.py

Turns out the type was a bit faulty (there was no way to have the CRS as None even before), led to some simplifications

Fix dataset CRS getter in geometry_io

---

core/eolearn/core/__init__.py
core/eolearn/core/core_tasks.py
core/eolearn/core/eodata.py
core/eolearn/core/eodata_merge.py

After sleeping on it it feels more correct to handle the circular import inside the deprecated method, rather than having weird wrappers. Also goes along with your instinct that the wrapper could be removed.

Move merge_eopatches to eodata_merge

---

ml_tools/eolearn/ml_tools/tdigest.py

As written in the [enhancement request](https://github.com/sentinel-hub/eo-learn/issues/637), there is a necessity for enabling the filtering of nan-values within the features used for the tdigest representation. The Pull-Request enables the Task to do so and, additionally, enables the users to provide own processing functions such as monthly per year accumulations, for example.
@zigaLuksic @batic Would be really happy if you could include it to eo-learn! Later, one should definitely take care of the underlying tdigest-implementation but that's something for another Pull-Request.

TDigestTask enabling nanfiltering and insertion of own processing functions.

---

core/eolearn/core/eodata_io.py
core/eolearn/tests/test_eodata_io.py

This is meant to set the stage for the future Zarr backend
When prototyping it became obvious that the burnt-in GZIP only made sense when all compression was done through it. With Zarr that will no longer be the case. Decided to do it separately to keep MRs small.
I also moved away from shpy MimeType class for file extensions, because it's annoying to first update sh-py whenever we add a new supported file format
I still do not like how `save` has a `compression_level` since that is again very GZIP specific, but I'd prefer to resolve that at a later point, when I have a better idea on how to handle FeatureIO classes with different parameters (since we'll have temporal indices and whatnot).

Refactor feature io classes

---

core/eolearn/core/extra/ray.py
core/eolearn/core/graph.py
core/eolearn/core/utils/parallelize.py

The `_` prefix was originally added to avoid issues with docs, but it turns out there are no issues with docs (type vars are not included) and the prefix-free notation is easier on the eyes in IDEs

Change typevar names

---

core/eolearn/core/eodata.py
core/eolearn/core/eodata_merge.py
core/eolearn/tests/test_eodata.py
core/eolearn/tests/test_eodata_merge.py
features/eolearn/features/doubly_logistic_approximation.py
features/eolearn/features/feature_manipulation.py
features/eolearn/features/interpolation.py
features/eolearn/features/temporal_features.py
geometry/eolearn/geometry/transformations.py
io/eolearn/io/extra/meteoblue.py
io/eolearn/io/raster_io.py
visualization/eolearn/visualization/eopatch.py

This establishes a separation of Patches with no temporal dimension and those with a zero-sized temporal dimension.
Also forces users to think about the possibility of not having timestamps available.
The `get_timestamps` method was added because most of the time we want an error to be raised if timestamps are missing.

Switch "no timestamps" value to `None`

---

core/eolearn/core/eodata_io.py
core/eolearn/tests/test_eodata_io.py

EOPatches with a null-sized temporal dimension did not save timestamps correctly.

Fix temporally empty io

---

core/eolearn/core/core_tasks.py
core/eolearn/core/eodata.py
core/eolearn/core/eodata_io.py
core/eolearn/core/eoworkflow_tasks.py
core/eolearn/tests/test_eodata.py
core/eolearn/tests/test_eodata_io.py
core/eolearn/tests/test_eoworkflow_tasks.py

The users have control over whether or not timestamps get saved, but it's set to `"auto"` by default which saves/loads timestamps if there are any temporal features being saved/loaded.
In the future any temporal-information-containing eopatches will REQUIRE timestamps. If users dont save/load them, it's their problem, should've left it on "auto".

Automate timestamp saving

---

core/eolearn/core/eodata_io.py
core/eolearn/tests/test_eodata_io.py

Bug occurred when we merged temporally-partial saving and the changes to timestamp saving.

fix bug where temporally-partial saving overwrites timestamps

---

core/eolearn/core/eodata_io.py
core/eolearn/tests/test_eodata_io.py

another :cookie: for my cuties
using `temporal_selection="infer"` when saving can now initialize Zarr arrays (provided timestamps are saved)

Infer can initialize zarr

---

core/eolearn/tests/test_eoexecutor.py

I was also considering:
- restricting ray versions (introduces nasty restrictions that we must remember to update once ray fixes stuff)
- warning users that logging wont work for bad ray versions (but it really shouldn't be our responsibility to clean up after them)
- trying to patch loggers (lots of work, too much for a known bug that is worked on)
This option will make our tests pass, if ray 2.6.2 still doesn't fix the mistake we will be notified, and if we forget about this and it stays in the tests for another 3 years it does no harm.

Adjust EOExecutor tests to pass until ray fixes logging

---

eolearn/core/eoworkflow_tasks.py

In the case that the OutputTask gets an EOPatch, it should output the patch fully (with timestamps)
Currently timestamps are discarded if there are no other temporal features, but the EOPatch must match the one that the task recieved.

Make OutputTask always output timestamps if any

---

eolearn/features/feature_manipulation.py
eolearn/features/utils.py
pyproject.toml

As discussed, this removes Pillow from the list of requirements. It is still installed as part of sh-py, but we might get rid of it in the future.

Switch default resize backend

---

eolearn/core/eodata_io.py
tests/core/test_eodata_io.py
tests/core/test_eodata_merge.py

We decided that since we do not support partial numpy saving, we shouldn't support partial numpy loading either.

Remove partial loading for numpy arrays

---

eolearn/core/eodata.py
tests/core/test_eodata.py

Previously "auto" only copied timestamps if there were any temporal features, but if you do `eopatch.copy()` you want an identical patch. So now when all features are being copied (i.e. `...`) the timestamps are also copied.

Copying an EOPatch copies timestamps if `features=...`

---

eolearn/core/eonode.py
eolearn/core/eoworkflow.py
eolearn/visualization/eoexecutor.py
eolearn/visualization/report_templates/report.html
tests/core/test_eoworkflow.py
tests/visualization/test_eoexecutor.py

Exceptions are now grouped by exception origin instead of error message (which often contains unique information and is thus unsuitable for grouping).
the summary also contains a list of all failed executions (per error)
(added screenshot of test case, the button toggles visibility)

Better exception grouping in reports

---

eolearn/mask/cloud_mask.py
tests/mask/test_cloud_mask.py

This is one part of multiple cloud-mask-split MRs. This is just to split the simplified cloud mask task from the complex legacy one.
In the next MR we will use the classifier code from `s2cloudless`

Split cloud mask task

---

eolearn/mask/cloud_mask.py
mask/requirements.txt
pyproject.toml

Changes:
- new requirement for `eo-learn-mask` (s2cloudless)
- simplified `CloudMaskTask` after using `S2PixelCloudDetector` from `s2cloudless`
I expected the test data to change and the tests to fail, since the eo-learn version was using a different version of the s2cloudless model (or seemed to be). Doesn't seem to be any change in the tests, so this one is a freebie.

Cloud mask task should use s2cloudless

---

eolearn/core/eodata_io.py
tests/core/test_eodata_io.py

When `load_timestamps=True` is set, the loading fails if there are no timestamps available.

Explicit loading timestamps fails if none are found

---

eolearn/core/eodata_io.py
pyproject.toml
tests/core/test_eodata_io.py

IOErrors to OSErrors

---

eolearn/core/utils/testing.py
eolearn/geometry/morphology.py
tests/geometry/test_morphology.py

Changes:
- remove usage of `skimage`
- introduce usage of `cv2`
- remove some things not obvious in cv2 (diamond kernel, etc.)
- update tests

Switch morphology tasks to use cv2 instead of skimage

---

eolearn/mask/cloud_mask.py
eolearn/mask/snow_mask.py

Note: 
- In cloud masking legacy task we used `cv2_disk` from `s2cloudless`, which is a bit different than what we used in morphology

Use cv2 in eolearn.mask

---

eolearn/io/raster_io.py
eolearn/ml_tools/sampling.py

Sometimes **kwargs do a lot of heavy lifting, sometimes they prevent the IDE and typecheckers from doing their work.
We are starting to favor reliability, so these need to go, even if it bloats the code a bit.

Explicit arguments in tasks instead of **kwargs

---

eolearn/core/core_tasks.py
eolearn/core/eodata.py
eolearn/core/eodata_io.py
tests/core/test_eodata_io.py

Changes:
- `compression_level` parameter removed
- compress by default for everything except bbox and timestamps
- test updates

Compression changes to eo-learn

---

eolearn/core/eodata.py
tests/core/test_eodata.py
tests/core/test_eodata_io.py
tests/core/test_eodata_merge.py
tests/features/conftest.py

I am open to adjust the input types.
If this gets merged I also think that we should add a corresponding task (that would then be suggested as a replacement for `FilterTimeSeriesTask`)

Add temporal filtration method

---

eolearn/core/__init__.py
eolearn/core/core_tasks.py
eolearn/core/eodata.py
tests/core/test_core_tasks.py
tests/core/test_eodata.py

Also improve the input type to support stronger callables

Add temporal subset task

---

CHANGELOG.md
eolearn/core/eoexecution.py
tests/core/test_eoexecutor.py

Do you think this might be useful?

Add option to treat temporal warnings as errors in eoexecutions

---

CHANGELOG.md
eolearn/core/eodata.py

Turns out dictionaries were never covered. Also any object other than `tuple` or `list` would just be printed out in full. And if the element inside a list was huge, why not, print that fully as well...
So what i did is make sure that:
- Every element with a representation that is too large gets shortened to `str(type(x))`
- Dictionaries follow a similar set of rules as tuples and lists (print first element and show length)
- When doing the above, the first element is recursively formatted with the same function
- I switched from `[x, ...], length=100` to `[x, ...]<length=100>` otherwise recursive nesting was unreadable since you got `[[x, ...], length=100], length=100`, but `[[x, ...]<length=100>, ...]<length=100>` is a bit better.
Example of how it works now:

Adjust EOPatch repr method

---

eolearn/core/eoexecution.py
eolearn/core/extra/ray.py
eolearn/visualization/eoexecutor.py
eolearn/visualization/report_templates/report.html
tests/core/test_eoexecutor.py
tests/core/test_extra/test_ray.py

Wanted to figure out where to push in the ray kwargs and decided to clean up a bit first.

Refactor eoexecutor

---

eolearn/visualization/eoexecutor.py

I had a hunch that i screwed something up with logs.
Ran some eo-grow pipelines and found out that i forgot to make paths relative

Fix mistake of logs paths being absolute

---

eolearn/core/eoexecution.py
eolearn/core/extra/ray.py
tests/core/test_extra/test_ray.py

Kinda hard to test :/ ideas welcome

Ray executor can request resources for workers

---

eolearn/io/raster_io.py
pyproject.toml
tests/io/test_raster_io.py

Cant really mock tests sadly. Tested it out and it seemed to work fine.

import tiffs now lets rasterio do it's thing

---

eolearn/io/raster_io.py
tests/io/test_raster_io.py

It's often not a folder, so it's very confusing...
Ellipsis as a default seemed like the best way to signal that this might still be required (using `None` would be odd).
- `TiffTask(feature, my_path)` works as before
- `TiffTask(feature)` will raise a `TypeError` that the parameter `path` is missing (similar to what would happen before)
- `TiffTask(feature, path=my_path)` works as intended
- `TiffTask(feature, folder=my_path)` also works as previously intended, but also warns the user

Tiff tasks parameter `folder` renamed to `path`

---

.github/workflows/ci_action.yml
.github/workflows/ci_trigger.yml
.gitlab-ci.yml

Some context:
- removed gitlab mirror + CI job from the old actions file
- created a new actions file which is triggered in all old cases + on releases
- there are multiple release types, more info [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release)
- `$GITHUB_REF` env variable is sent to gitlab as well, which starts with `refs/tags/` for releases. this info is used so that docker build is not triggered on push/PR/scheduled events
We can test this by creating a draft release, and then we can also delete it if need be. When everything is tested, only the published release type should trigger the docker build in gitlab

Enable github to trigger internal gitlab docker image build

---

.github/workflows/ci_action.yml
.github/workflows/ci_trigger.yml
.gitlab-ci.yml

Instead of triggering gitlab CI/CD for docker builds via the mirroring action

Use trigger API to build internal docker

---

eolearn/coregistration/coregistration.py
eolearn/features/utils.py
eolearn/mask/snow_mask.py
tests/mask/test_snow_mask.py

Was easier to return something early, instead of fixing the shapes

Fix SnowMaskTask when dealing with empty patches
